version: 1.0.{build}

init:
# Good practise, because Windows line endings are different from Unix/Linux ones
- cmd: git config --global core.autocrlf true

- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
  
install:
- cmd: >-   
    npm install -g bower

before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    # Display minimal restore text
    - cmd: dotnet restore ./ReAl.Template.MaterialAdmin/ReAl.Template.MaterialAdmin.csproj --verbosity m
    
build_script:
    # output will be in ./src/bin/debug/netcoreapp1.1/publish
    - cmd: dotnet publish ./ReAl.Template.MaterialAdmin/ReAl.Template.MaterialAdmin.csproj
after_build:
    # For once the build has completed
artifacts:
- path: '\ReAl.Template.MaterialAdmin\bin\Debug\netcoreapp2.0\publish'
  name: MaterialAdmin

clone_depth: 1
on_finish :
    # any cleanup in here
    - cmd: ./ReAl.Template.MaterialAdmin/before-deploy.ps1

deploy:
- provider: WebDeploy
  artifact: MaterialAdmin
  aspnet_core: true
  aspnet_core_force_restart: true
  app_offline: true